channels:
- conda-forge
dependencies:
- python=3.11.5
- pip<=23.2.1
- pip:
  - mlflow==2.19.0
  - cloudpickle==3.1.2
  - numpy==2.4.0
  - pandas==2.3.3
  - psutil==7.2.0
  - pyarrow==18.1.0
  - scikit-learn==1.8.0
  - scipy==1.16.3
  - dagshub
  - boto3
name: mlflow-env